#### function to execute Beagle4.1



##wrap function to impute with beagle 4.1 for batchtools
#data as defined by batchtools call, which is the data to be imputed
#job and instance is defined by batchtools call
#exec expexts the path to the Beagle4.1 Executable
#outpref expects a path with a prefix of how the output files should be named.
#     the full name will be generated by the function including the phasing process, imputation process and chunk
#plink.map expects the path to the map file in plink format
#reference.vcf expects the path to the reference panel in vcf format
# int marks the start of the chunk
#chr.flag needs to be set according to which chromosome is the imputation carried out on
beagle4_wrap <- function(data, 
                         job,
                         instance,
                         exec,
                         outpref,
                         plink.map,
                         reference.vcf,
                         int,
                         chr.flag) {
    # outpref ist prefix an das noch der counter drangehangen wird
    
    #check cromosome flag for right chunking
    if(chr.flag==19){
        inte <- int + chunk_19 - 1
    }
    if(chr.flag==22){
        inte <- int + chunk_22 - 1
    }
    
    
    #define chunks
    intstring1 <- toString(format(int, scientific = F))
    intstring2 <- toString(format(inte, scientific = F))
    
    #define name of the output file
    out <- paste(outpref,
                 instance[2],
                 chr.flag,
                 intstring1,
                 sep = "_")
    
    #set seed
    draw_seed <- sample(1:9999, 1)
    
    #use Beagle4.1
    system2(dir_exec_java,
            c("-jar",
              exec,
              paste("ref=", reference.vcf, sep = ""),
              paste("gt=", instance[1], ".vcf.gz", sep = ""),
              paste("map=", plink.map, sep = ""), 
              paste("out=", out, sep = ""), 
              paste("chrom=",chr.flag,":", intstring1, "-", intstring2, sep = ""),
              paste("seed=", draw_seed, sep = ""),
              "nthreads=1 gprobs=true"))
    
    #return path of the output file
    return(paste(out, ".vcf.gz", sep = ""))
}
