#function to execute Beagle5.1

##wrap function to impute with Beagle 5.1 for batchtools
#data as defined by batchtools call, which is the data to be imputed
#job and instance is defined by batchtools call
#exec expexts the path to the Beagle5.1 Executable
#outpref expects a path with a prefix of how the output files should be named.
#     the full name will be generated by the function including the phasing process, imputation process and chunk
#plink.map expects the path to the map file in plink format
#reference.bref3 expects the path to the reference panel in bref3 format
# int marks the start of the chunk
#chr.flag needs to be set according to which chromosome is the imputation carried out on
beagle5_impute_wrap <- function(data, 
                                job,
                                instance,
                                exec,
                                outpref,
                                plink.map,
                                reference.bref3,
                                int,
                                chr.flag) {
    
    
    #check cromosome flag for right chunking
    if(chr.flag==19){
        inte <- int + chunk_19 - 1
    }
    if(chr.flag==22){
        inte <- int + chunk_22 - 1
    }
    
    
    #define chunks
    intstring1 <- toString(format(int, scientific = F))
    intstring2 <- toString(format(inte, scientific = F))
    
    #draw seed
    draw_seed <- sample(1:9999, 1)
    
    #define output name    
    out <- paste(outpref,
                 instance[2],
                 chr.flag,
                 intstring1,
                 sep = "_")
    
    #use Beagle5 for imputation
    system2(dir_exec_java,
            c("-jar",
              exec,
              paste("ref=", reference.bref3, sep = ""),
              paste("gt=", instance[1], ".vcf.gz", sep = ""),
              paste("out=", out, sep = ""),
              paste("map=", plink.map, sep = ""),
              paste("chrom=",chr.flag,":", intstring1, "-", intstring2, sep = ""),
              paste("seed=", draw_seed, sep = ""),
              "nthreads=1 gp=true"))
    
    #return path to output file
    return(paste(out, ".vcf.gz", sep = ""))
    
}



##wrap function to phase with Beagle 5.1 for batchtools
#data as defined by batchtools call, which is the data to be imputed
#jobe is defined by batchtools call
#exec expexts the path to the Beagle5.1 Executable
#outpref expects a path with a prefix of how the output files should be named.
#     the full name will be generated by the function including the phasing process suffix for data type
#plink.map expects the path to the map file in plink format
#chr.flag needs to be set according to which chromosome is the imputation carried out on
beagle5_phasing_wrap <- function(data,
                                 job,
                                 exec,
                                 outpref,
                                 plink.map,
                                 chr.flag
                                 ) {
    
  #phase data set with external function
    phased <- beagle5_phasing_phase(data,
                                    exec,
                                    outpref,
                                    plink.map
                                    )
    
    
    #converts output from vcf to haps for imputation with IMPUTE2 and IMPUTE4
    vcf_hap(phased)
    file.rename(paste(phased, ".hap.gz", sep = ""), paste(phased, ".haps.gz", sep = ""))
    
    
    #check cromosome flag to prepare data set for imputation with PBWT
    if(chr.flag==19){
      ref_pbwt_prep<-dir_input_reference_vcf_annotated_19
    }
    if(chr.flag==22){
      ref_pbwt_prep<-dir_input_reference_vcf_annotated_22
    }
    
    #create extra output file for PWBWT Imputation
    pbwt_prep(phased, ref_pbwt_prep, "phased_beagle5", chr.flag)
    
    #return location and prefix of phased dataset and flag for which phasing was used. 
    #Later functions will add the needed suffix for the data type themselves
    return(c(outpref, "phased_beagle5"))
}

##phase with beagle5.1
beagle5_phasing_phase <- function(data, exec, outpref, plink.map) {
    
  #set seed
    draw_seed <- sample(1:9999, 1)
  #execute phasing with Beagle 5.1  
    system2(dir_exec_java,
            c("-jar",
              exec,
              paste("gt=", data, sep = ""),
              paste("out=", outpref, sep = ""),
              paste("map=", plink.map, sep = ""),
              paste("seed=", draw_seed, sep = ""),
              "nthreads=1 impute=false"))
    
    return(outpref)
}
