####phasing with eagle


# input: data= path to data to phase in vcf,gz job exec points to eagle2 map= path that points to txt file with genetic map (4 columns) out= path pointing to the
# not-yet extistint outputfile reference.vcf= path pointing to referencepanel ref.on= 0 or 1 binary, 0 phases without refpanel, 1 phases with refpanel

# ouput: path to now existing outputfile in vcf.gz


##wrap function to phase with eagle for batchtools
#data as defined by batchtools call, which is the data to be imputed
#jobe is defined by batchtools call
#exec expexts the path to the eagle Executable
#outpref expects a path with a prefix of how the output files should be named.
#     the full name will be generated by the function including the phasing process suffix for data type
#map.with.chr expects the path to the map file inlcuding a chromosome column
#chr.flag needs to be set according to which chromosome is the imputation carried out on
#reference.vcf expects the path to the reference panel in vcf form
#ref.on is a flag, TRUE means the phasing will be carried out with the reference panel
eagle_wrap <- function(data,
                       job,
                       exec,
                       outpref,
                       map.with.chr,
                       reference.vcf,
                       ref.on, 
                       chr.flag, ...) {
    
  #phasing, if reference panel should be included
    if (ref.on) {
        system2(exec, c("--vcfTarget", data,
                        "--vcfRef", reference.vcf,
                        "--outPrefix", paste(outpref, "_mit_ref", sep = ""),
                        "--vcfOutFormat z", "--geneticMapFile", map.with.chr, 
            "2>&1 | tee ", paste(paste(outpref, "_mit_ref", sep = ""), "log", sep = ".")))
        
      #create new file in hap format for imputation with IMPUTE2 and IMPUTE4
        vcf_hap(paste(outpref, "_mit_ref", sep = ""))
      #rename for consistency  
        file.rename(paste(outpref, "_mit_ref", ".hap.gz", sep = ""), paste(outpref, "_mit_ref", ".haps.gz", sep = ""))
      #create new file for imputation with PBWT
        pbwt_prep(paste(outpref, "_mit_ref", sep = ""), reference.vcf, "phased_eagle_ref_on", chr.flag)
        #return location and prefix of phased dataset and flag for which phasing was used. 
        #Later functions will add the needed suffix for the data type themselves
        return(c(paste(outpref, "_mit_ref", sep = ""), "phased_eagle_ref_on"))
    } else {
      #phasing, if reference panel is not included, step description analogous to description above
        system2(exec, c("--vcf", data, "--outPrefix", paste(outpref, "_ohne_ref", sep = ""),
                        "--geneticMapFile", map.with.chr, "2>&1 | tee ", paste(outpref, "log", sep = ".")))
        
        vcf_hap(paste(outpref, "_ohne_ref", sep = ""))
        file.rename(paste(outpref, "_ohne_ref", ".hap.gz", sep = ""), paste(outpref, "_ohne_ref", ".haps.gz", sep = ""))
        pbwt_prep(paste(outpref, "_ohne_ref", sep = ""), reference.vcf, "phased_eagle_ref_off",chr.flag)
        
        return(c(paste(outpref, "_ohne_ref", sep = ""), "phased_eagle_ref_off"))
    }
  
}
