# minimac4

##wrap function to impute with minimac4 for batchtools
#data as defined by batchtools call, which is the data to be imputed
#job and instance is defined by batchtools call
#exec expexts the path to the minimac4 Executable
#outpref expects a path with a prefix of how the output files should be named.
#     the full name will be generated by the function including the phasing process, imputation process and chunk
#map.with.chr expects the path to the map file with a column for the chromosome
#reference.m3vcf expects the path to the reference panel in m3vcf format
# int marks the start of the chunk
#chr.flag needs to be set according to which chromosome is the imputation carried out on

minimac4_wrap <- function(data, 
                          job,
                          instance,
                          exec, 
                          outpref,
                          map.with.chr,
                          reference.m3vcf,
                          int,
                          chr.flag) {
    
    
    #check cromosome flag for right chunking
    if(chr.flag==19){
        inte <- int + chunk_19 - 1
    }
    if(chr.flag==22){
        inte <- int + chunk_22 - 1
    }
    
    #define chunks
    intstring1 <- toString(format(int, scientific = F))
    intstring2 <- toString(format(inte, scientific = F))
    
    #define output path
    out <- paste(outpref, instance[2], chr.flag, intstring1, sep = "_")
    
    #execute imputation with minimac4
    system2(exec, c("--haps", paste(instance[1], ".vcf.gz", sep = ""),
                    "--refHaps", reference.m3vcf, 
                    "--mapFile", map.with.chr, 
                    "--prefix", out,
                    "--chr", chr.flag,
                    "--start", intstring1, "--end", intstring2,
                    "--ChunkOverlapMb 0.5 --cpus 1 --format GP",
                    "--minRatio 0.01"))
    
    #return path to imputed file
    return(paste(out, "dose", "vcf", "gz", sep = "."))
}
