## shapeit 1)phasing with shapeit 2) converting with shapeit 3) wrap function


##wrap function to phase with Shapeit for batchtools
#data as defined by batchtools call, which is the data to be imputed
#jobe is defined by batchtools call
#exec expexts the path to the Shapeit Executable
#outpref expects a path with a prefix of how the output files should be named.
#     the full name will be generated by the function including the phasing process suffix for data type
#map.no.chr expects a map wfile without a column for chromosomes
#chr.flag needs to be set according to which chromosome is the imputation carried out on
#ref.on is a flag for the inlcusion of a reference panel 
#reference.hap expects the path to a reference panel in the .hap format
shapeit_wrap <- function(data,
                         job,
                         exec,
                         outpref,
                         map.no.chr,
                         reference.hap,
                         ref.on,
                         chr.flag) {
    
    #phasing with external function
    phased <- shapeit_phase(data, 
                            exec,
                            outpref,
                            map.no.chr,
                            reference.hap,
                            ref.on,
                            chr.flag)
    
    # converting phased data into vcf format
    conv <- shapeit_conv(phased, exec)
    
    
    #check flag to choose right reference for pbwt_prep
    if(chr.flag==19){
      ref_pbtw_prep<- dir_input_reference_vcf_annotated_19
    }  
    if(chr.flag==22){
      ref_pbtw_prep<- dir_input_reference_vcf_annotated_22
    }   
    
    
    #call pbtw_prep to prepare output for imputation with pbwt and
    # set phasing flag for the previous process according to ref.on
    if (ref.on) {
        pbwt_prep(phased, ref_pbtw_prep, "phased_shapeit_ref_on",chr.flag)
        return(c(conv, "phased_shapeit_ref_on"))
    } 
    else {
        pbwt_prep(phased, ref_pbtw_prep, "phased_shapeit_ref_off", chr.flag)
        return(c(conv, "phased_shapeit_ref_off"))
    }
}



#phasing with shape it
shapeit_phase <- function(data, exec, outpref, map, reference.hap, ref.on, chr.flag) {
  #set seed  
  draw_seed <- sample(1:9999, 1)
    
  #phasing with reference panel
  if (ref.on) {
    #check which chromosome should be phased, get exclusion file accordingly 
      if(chr.flag==19){
        dir_input_exclude_shapeit<- dir_input_exclude_shapeit_19
      }  
      if(chr.flag==22){
        dir_input_exclude_shapeit<- dir_input_exclude_shapeit_22
      }   
      #execute phasing with shapeit
      system2(exec, c("--input-vcf", data,
                      "-M", map,
                      "--input-ref", paste(reference.hap, ".hap.gz", sep = ""), 
                      paste(reference.hap, ".legend.gz", sep = ""), 
                      paste(reference.hap, ".samples", sep = ""),
                      "--exclude-snp", paste(dir_input_exclude_shapeit, ".snp.strand.exclude", sep = ""), 
                      "--seed", draw_seed, 
                      "-O", paste(outpref, "_mit_ref", sep = ""),
                      "-L", paste(outpref, "_mit_ref", ".log", sep = "")))
      #return file path to phased data set  
      return(paste(outpref, "_mit_ref", sep = ""))
  }
  #phasing without reference panel
  else {
    
    #execute phasing without reference
        system2(exec, c("--input-vcf", data, "-M", map, "-O", paste(outpref, "_ohne_ref", sep = ""), "-L", paste(outpref, "_ohne_ref.log", sep = ""), "--seed", draw_seed))
    #return file path to phased data set  
        return(paste(outpref, "_ohne_ref", sep = ""))
    }
    
}

#create new file with converted shapeit output in .vcf format
shapeit_conv <- function(data, exec) {
    system2(exec, c("-convert",
                    "--input-haps", data,
                    "--output-vcf",
                    paste(data, ".vcf", sep = ""),
                    "-L", paste(data, "conv.log", sep = "")))
    
    system2(dir_exec_bgzip, paste(data, ".vcf", sep = ""))
    return(data)
}



#check for SNPs to exclude for phasing with reference panel
shapeit_prep <- function(data, exec, outpref, reference.hap) {
    
    system2(exec, c("-check --input-vcf", data, 
                    "--input-ref",
                    paste(reference.hap, ".hap.gz", sep = ""),
                    paste(reference.hap, ".legend.gz", sep = ""),
                    paste(reference.hap, 
        ".samples", sep = ""), "--output-log", outpref))
    
    return(outpref)
}


